# Generated by Django 5.2.4 on 2025-07-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BonusRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("always", "Always applies"),
                            ("is_weekend_or_holiday", "Weekend or Holiday"),
                            ("customer_status", "Customer Status"),
                        ],
                        max_length=32,
                    ),
                ),
                ("condition_value", models.JSONField(blank=True, null=True)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("base", "Base bonus per amount"),
                            ("multiply", "Multiply bonus"),
                            ("percent_add", "Add percentage to bonus"),
                        ],
                        max_length=32,
                    ),
                ),
                ("operation_value", models.JSONField()),
                ("priority", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["priority"],
            },
        ),
    ]
