# Generated by Django 5.2.4 on 2025-07-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bonus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BonusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_code", models.CharField(max_length=100)),
                ("bonus_delta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_bonus", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
